### ISSUE TITLE
TOSA

### ISSUE THREAD

**Issue by bhack** [lfai/proposing-projects#29]
It would be nice to have Linaro/ARM TOSA spec handled by a vendor neutral initiative like LFAI.

Please check the thread https://llvm.discourse.group/t/rfc-tosa-dialect-in-mlir/1971

**Comment by bhack** [comment]
See also https://discuss.mlplatform.org/t/accepting-feedback-on-the-spec/50

**Comment by ibrahimhaddad** [comment]
Thanks @bhack. I am available to discuss with the project members.

**Comment by bhack** [comment]
@ibrahimhaddad I am not a project members but I think it could be a nice idea for LFAI
